repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3
        files: ^src/.*\.py$

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        files: ^src/.*\.py$
        args: [--max-line-length=88]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: ^src/.*\.py$

  - repo: local
    hooks:
      - id: colcon-build-check
        name: colcon build check
        entry: bash -c 'source /opt/ros/humble/setup.bash && colcon build --packages-select autonombot_launch autonombot_drivers'
        language: system
        pass_filenames: false
        files: \.(py|cpp|hpp|yaml|xml)$
