controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.3
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["general_goal_checker"]
    controller_plugins: ["FollowPath"]
    odom_topic: /autonombot_drivers/odom

    # Progress checker parameters
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.3
      movement_time_allowance: 15.0
    # Goal checker parameters
    general_goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.15
      yaw_goal_tolerance: 0.20
      stateful: True
    
    # RPP parameters
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.5   # Increased from 0.3 for better speed
      lookahead_dist: 1.2       # Increased for higher speeds
      min_lookahead_dist: 0.6   # Increased proportionally
      max_lookahead_dist: 1.8   # Increased for better planning
      lookahead_time: 2.0               # Balanced planning ahead
      rotate_to_heading_angular_vel: 1.5    # Increased from 0.8 for better turning
      transform_tolerance: 0.2
      use_velocity_scaled_lookahead_dist: true  # Enable dynamic lookahead
      min_approach_linear_velocity: 0.005   # Much slower approach (was 0.01)
      approach_velocity_scaling_dist: 5.0   # Start slowing down MUCH earlier (was 3.5m)
      use_collision_detection: true
      max_allowed_time_to_collision_up_to_carrot: 5.0  # Much more safety time (was 3.5s)
      use_regulated_linear_velocity_scaling: true
      use_cost_regulated_linear_velocity_scaling: true
      regulated_linear_scaling_min_radius: 1.5          # Slightly reduced for better flow
      regulated_linear_scaling_min_speed: 0.03          # Increased minimum speed slightly
      use_fixed_curvature_lookahead: false
      curvature_lookahead_dist: 1.0
      use_rotate_to_heading: true
      rotate_to_heading_min_angle: 0.524    # 30 degrees
      max_angular_accel: 2.0                # Balanced angular acceleration
      max_robot_pose_search_dist: 10.0
      interpolate_curvature_after_goal: false
      cost_scaling_dist: 0.8                # Slightly reduced for better flow
      cost_scaling_gain: 2.5                # Balanced cost sensitivity  
      inflation_cost_scaling_factor: 10.0   # Maintained high inflation response

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 30.0        # Increased for more responsive obstacle detection
      publish_frequency: 20.0       # Increased for better real-time updates
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: true
      rolling_window: true
      width: 8                      # Increased for better forward visibility
      height: 8                     # Increased for better obstacle coverage
      resolution: 0.05
      robot_radius: 0.18            # Increased robot radius for more safety margin
      transform_tolerance: 0.3
      plugins: ["obstacle_layer", "inflation_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 8.0        # Balanced - strong avoidance but allows planning
        inflation_radius: 1.2           # Safe margin but not excessive
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan vision_obstacles
        track_unknown_space: false
        max_obstacle_height: 2.0
        combination_method: 1           # Maximum combination for safety
        footprint_clearing_enabled: true
        max_obstacle_height: 2.0
        min_obstacle_height: 0.0
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True              # Enable clearing old obstacles
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 4.0    # Increased for better clearing
          raytrace_min_range: 0.0
          obstacle_max_range: 4.0     # Increased range for better detection
          obstacle_min_range: 0.05    # CRITICAL: Detect obstacles from 5cm minimum!
          observation_persistence: 2.0 # Increased persistence for safety
          expected_update_rate: 20.0   # Expect 20Hz updates from laser
        vision_obstacles:
          topic: /vision_obstacles
          max_obstacle_height: 2.0
          clearing: False
          marking: True
          data_type: "PointCloud2"
          raytrace_max_range: 2.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.05    # CRITICAL: Vision obstacles from 5cm minimum!
          observation_persistence: 8.0
          expected_update_rate: 0.0
      always_send_full_costmap: True
