controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.3
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["general_goal_checker"]
    controller_plugins: ["FollowPath"]
    odom_topic: /autonombot_drivers/odom

    # Progress checker parameters
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.3
      movement_time_allowance: 15.0
    # Goal checker parameters
    general_goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.15
      yaw_goal_tolerance: 0.20
      stateful: True
    
    # RPP parameters
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.3
      lookahead_dist: 0.6
      min_lookahead_dist: 0.3
      max_lookahead_dist: 0.9
      lookahead_time: 1.5
      rotate_to_heading_angular_vel: 1.8
      transform_tolerance: 0.2
      use_velocity_scaled_lookahead_dist: false
      min_approach_linear_velocity: 0.02
      approach_velocity_scaling_dist: 1.5
      use_collision_detection: true
      max_allowed_time_to_collision_up_to_carrot: 2.0
      use_regulated_linear_velocity_scaling: true
      use_cost_regulated_linear_velocity_scaling: true
      regulated_linear_scaling_min_radius: 1.2
      regulated_linear_scaling_min_speed: 0.15
      use_fixed_curvature_lookahead: false
      curvature_lookahead_dist: 1.0
      use_rotate_to_heading: true
      rotate_to_heading_min_angle: 0.785
      max_angular_accel: 3.2
      max_robot_pose_search_dist: 10.0
      interpolate_curvature_after_goal: false
      cost_scaling_dist: 0.3
      cost_scaling_gain: 1.0
      inflation_cost_scaling_factor: 3.0

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 20.0        # Increased for more responsive obstacle detection
      publish_frequency: 15.0       # Increased for better real-time updates
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: true
      rolling_window: true
      width: 6                      # Increased for better forward visibility
      height: 6                     # Increased for better obstacle coverage
      resolution: 0.05
      robot_radius: 0.1
      transform_tolerance: 0.3
      plugins: ["obstacle_layer", "inflation_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 5.0
        inflation_radius: 1.0
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan vision_obstacles
        track_unknown_space: false
        max_obstacle_height: 2.0
        combination_method: 0
        footprint_clearing_enabled: true
        max_obstacle_height: 2.0
        min_obstacle_height: 0.0
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True              # Enable clearing old obstacles
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 3.5     # Increased range for better detection
          obstacle_min_range: 0.0
          observation_persistence: 1.0 # Reduced persistence for more responsive updates
          expected_update_rate: 20.0   # Expect 20Hz updates from laser (increased from 10Hz)
        vision_obstacles:
          topic: /vision_obstacles
          max_obstacle_height: 2.0
          clearing: False
          marking: True
          data_type: "PointCloud2"
          raytrace_max_range: 2.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
          observation_persistence: 8.0
          expected_update_rate: 0.0
      always_send_full_costmap: True
