planner_server:
  ros__parameters:
    expected_planner_frequency: 1.0
    use_sim_time: true
    planner_plugins: ["GridBased"]

    # Smac 2D parameters - Confident Navigation Through Tight Spaces
    GridBased:
      plugin: "nav2_smac_planner/SmacPlanner2D" 
      tolerance: 0.15                       
      downsample_costmap: false             # whether or not to downsample the map
      downsampling_factor: 1                # multiplier for the resolution of the costmap layer (e.g. 2 on a 5cm costmap would be 10cm)
      allow_unknown: true                   # allow traveling in unknown space
      max_iterations: 2000000               # increased iterations for complex scenarios
      max_on_approach_iterations: 2000      # more attempts to reach goal
      max_planning_time: 3.0                # reasonable planning time
      cost_travel_multiplier: 1.8           # balanced to maintain safe distance from obstacles
      use_final_approach_orientation: false # Whether to set the final path pose at the goal's orientation to the requested orientation (false) or in line with the approach angle so the robot doesn't rotate to heading (true)
      smoother:
        max_iterations: 1000
        w_smooth: 0.3
        w_data: 0.2
        tolerance: 1.0e-10

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 3.0
      publish_frequency: 2.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: true
      robot_radius: 0.18          # Made consistent with local costmap
      resolution: 0.05
      track_unknown_space: true
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan vision_obstacles
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: False
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.5
          raytrace_min_range: 0.0
          obstacle_max_range: 2.8
          obstacle_min_range: 0.05      # CRITICAL: Detect obstacles from 5cm minimum!
          observation_persistence: 10.0
        vision_obstacles:
          topic: /vision_obstacles
          max_obstacle_height: 2.0
          clearing: False
          marking: True
          data_type: "PointCloud2"
          raytrace_max_range: 2.5
          raytrace_min_range: 0.0
          obstacle_max_range: 3.0
          obstacle_min_range: 0.05      # CRITICAL: Vision obstacles from 5cm minimum!
          observation_persistence: 10.0
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_topic: /map
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 8.0        # Strong obstacle avoidance cost gradients 
        inflation_radius: 1.2           # Balanced safety margin
      always_send_full_costmap: True