name: ROS 2 Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup ROS 2
      uses: ros-tooling/setup-ros@v0.7
      with:
        required-ros-distributions: humble
    
    - name: Install basic dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-colcon-common-extensions
        sudo apt-get install -y python3-pip
        sudo apt-get install -y ros-humble-navigation2
        sudo apt-get install -y ros-humble-nav2-bringup
        sudo apt-get install -y ros-humble-gazebo-ros-pkgs
        sudo apt-get install -y ros-humble-robot-localization
        sudo apt-get install -y ros-humble-xacro
    
    - name: Install Python dependencies
      run: |
        pip3 install ultralytics opencv-python numpy
      continue-on-error: true
    
    - name: Build workspace
      run: |
        source /opt/ros/humble/setup.bash
        colcon build --symlink-install --continue-on-error --packages-ignore autonombot_firmware
    
    - name: Check build results
      run: |
        if [ -d "install" ]; then
          echo "✅ Build completed successfully"
          ls -la install/
        else
          echo "❌ Build failed"
          exit 1
        fi
